### ISSUE TITLE
Implement a widget adapter for Angular 2

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar-angular2-adapter#1]
- [x] adapter loading widgets in the application
- [x] widgets can provide widget areas
- [x] widgets can use controls of that technology
- [x] write tests for the adapter
- [x] support testing of widgets for this adapter
- [x] document the adapter

may be a little later, but not too late:
- [ ] provide a yeoman generator for widgets using the new adapter

@x1B anything missing?

**Comment by x1B** [comment]
@alex3683 Looks like a good checklist that we should adopt for all of our technologies :)

**Comment by alex3683** [comment]
Testing widgets in general seems to work. One drawback though is missing Angular 2 TestBed and fixtures support (https://angular.io/docs/ts/latest/guide/testing.html). It would be great if the Angular specific parts of a widget would be testable just like standard Angular artifacts.

**Comment by alex3683** [comment]
Opened a ticket for the angular 2 widget generator in the yeoman generator repository (https://github.com/LaxarJS/generator-laxarjs/issues/24).

**Comment by alex3683** [comment]
Implemented on `master` (`v2.0.0-alpha.0`).
